### ISSUE TITLE
ECX follow-up. Urgent Attention Required

### ISSUE THREAD

**Issue by KeneNwogu** [drvnprgrmr/scissor#1]
Hello, you submitted this repository as your favourite project. It's great work, but you didn't send your contact details on the form. I would love to talk about the project. If you are still up for it, can you send your email as a comment on this issue?

Regards,
Kenechukwu.
Development Lead, ECX 5.0.

**Comment by drvnprgrmr** [comment]
Hi there!

Oh I didn't? Sorry about that. Maybe it wasn't a required field and I overlooked it. I thought I filled the form completely though.

**Comment by drvnprgrmr** [comment]
Oh, @KeneNwogu you already closed the issue. Have you seen the email address?

**Comment by KeneNwogu** [comment]
Oh yeah, I closed it, I think I already saw your email address
***@***.***?
